/**
 * @param {import('knex')} knex
 */
exports.seed = async (knex) => {
  await knex("courses")
    .del()
    .then(() => {
      return knex("courses").insert([
        { id: 1, name: "CBSE" },
        { id: 2, name: "Entrance Exam" },
        { id: 3, name: "Competitive Exams" },
        { id: 4, name: "ICSE & ISC" },
        { id: 5, name: "Others" },
      ]);
    });
  await knex("classes")
    .del()
    .then(() => {
      return knex("classes").insert([
        { id: 1, course_id: 1, name: "Class 01" },
        { id: 2, course_id: 1, name: "Class 02" },
        { id: 3, course_id: 1, name: "Class 03" },
        { id: 4, course_id: 1, name: "Class 04" },
        { id: 5, course_id: 1, name: "Class 05" },
        { id: 6, course_id: 1, name: "Class 06" },
        { id: 7, course_id: 1, name: "Class 07" },
        { id: 8, course_id: 1, name: "Class 08" },
        { id: 9, course_id: 1, name: "Class 09" },
        { id: 10, course_id: 1, name: "Class 10" },
        { id: 11, course_id: 1, name: "Class 11" },
        { id: 12, course_id: 1, name: "Class 12" },

        { id: 13, course_id: 2, name: "JEE main" },
        { id: 14, course_id: 2, name: "NEET-UG" },

        { id: 15, course_id: 3, name: "SSC CGL" },
        { id: 16, course_id: 3, name: "NDA" },

        { id: 17, course_id: 4, name: "Class 01" },
        { id: 18, course_id: 4, name: "Class 02" },
        { id: 19, course_id: 4, name: "Class 03" },
        { id: 20, course_id: 4, name: "Class 04" },
        { id: 21, course_id: 4, name: "Class 05" },
        { id: 22, course_id: 4, name: "Class 06" },
        { id: 23, course_id: 4, name: "Class 07" },
        { id: 24, course_id: 4, name: "Class 08" },
        { id: 25, course_id: 4, name: "Class 09" },
        { id: 26, course_id: 4, name: "Class 10" },
        { id: 27, course_id: 4, name: "Class 11" },
        { id: 28, course_id: 4, name: "Class 12" },

        { id: 29, course_id: 5, name: "Others" },
      ]);
    });
  await knex("subjects")
    .del()
    .then(() => {
      return knex("subjects").insert([
        { id: 1, class_id: 1, name: "English" },
        { id: 2, class_id: 1, name: "Hindi" },
        { id: 3, class_id: 1, name: "Mathematics" },
        { id: 4, class_id: 1, name: "EVS" },
        { id: 5, class_id: 1, name: "General Knowledge" },
        { id: 6, class_id: 1, name: "Computer" },
        { id: 7, class_id: 1, name: "Regional Language" },
        { id: 8, class_id: 1, name: "English - Marigold" },
        { id: 9, class_id: 1, name: "Mathematics - Math Magic" },
        { id: 10, class_id: 1, name: "हिंदी - रिमझिम" },
        { id: 11, class_id: 1, name: "Other Subjects" },

        { id: 12, class_id: 2, name: "English" },
        { id: 13, class_id: 2, name: "Hindi" },
        { id: 14, class_id: 2, name: "Mathematics" },
        { id: 15, class_id: 2, name: "EVS" },
        { id: 16, class_id: 2, name: "Other Subjects" },
        { id: 17, class_id: 2, name: "General Knowledge" },
        { id: 18, class_id: 2, name: "Computer" },
        { id: 19, class_id: 2, name: "Regional Language" },
        { id: 20, class_id: 2, name: "Mathematics - Math Magic" },
        { id: 21, class_id: 2, name: "English - Marigold" },
        { id: 22, class_id: 2, name: "हिंदी - रिमझिम" },

        { id: 23, class_id: 3, name: "Mathematics" },
        { id: 24, class_id: 3, name: "Science" },
        { id: 25, class_id: 3, name: "Social Science" },
        { id: 26, class_id: 3, name: "English - Marigold" },
        { id: 27, class_id: 3, name: "हिंदी - रिमझिम" },
        { id: 28, class_id: 3, name: "EVS - Looking Around" },
        { id: 29, class_id: 3, name: "Mathematics - Math Magic" },
        { id: 30, class_id: 3, name: "General Knowledge" },
        { id: 31, class_id: 3, name: "Computer" },
        { id: 32, class_id: 3, name: "Regional Language" },
        { id: 33, class_id: 3, name: "EVS" },
        { id: 34, class_id: 3, name: "Other Subjects" },

        { id: 35, class_id: 4, name: "Mathematics" },
        { id: 36, class_id: 4, name: "Social Science" },
        { id: 37, class_id: 4, name: "Science" },
        { id: 38, class_id: 4, name: "English - Marigold" },
        { id: 39, class_id: 4, name: "हिंदी - रिमझिम" },
        { id: 40, class_id: 4, name: "Mathematics - Math Magic" },
        { id: 41, class_id: 4, name: "EVS - Looking Around" },
        { id: 42, class_id: 4, name: "General Knowledge" },
        { id: 43, class_id: 4, name: "Computer" },
        { id: 44, class_id: 4, name: "Regional Language" },
        { id: 45, class_id: 4, name: "EVS" },
        { id: 46, class_id: 4, name: "Other Subjects" },

        { id: 47, class_id: 5, name: "Mathematics" },
        { id: 48, class_id: 5, name: "Science" },
        { id: 49, class_id: 5, name: "Social Science" },
        { id: 50, class_id: 5, name: "English - Marigold" },
        { id: 51, class_id: 5, name: "हिंदी - रिमझिम" },
        { id: 52, class_id: 5, name: "Mathematics - Math Magic" },
        { id: 53, class_id: 5, name: "EVS - Looking Around" },
        { id: 54, class_id: 5, name: "General Knowledge" },
        { id: 55, class_id: 5, name: "Computer" },
        { id: 56, class_id: 5, name: "Regional Language" },
        { id: 57, class_id: 5, name: "EVS" },
        { id: 58, class_id: 5, name: "Other Subjects" },

        { id: 59, class_id: 6, name: "Mathematics" },
        { id: 60, class_id: 6, name: "Science" },
        { id: 61, class_id: 6, name: "Social Science" },
        { id: 62, class_id: 6, name: "English" },
        { id: 63, class_id: 6, name: "हिंदी (वसंत और बाल राम कथा)" },
        { id: 64, class_id: 6, name: "Other Subjects" },
        { id: 65, class_id: 6, name: "Sanskrit" },
        { id: 66, class_id: 6, name: "Computer" },
        { id: 67, class_id: 6, name: "French" },
        { id: 68, class_id: 6, name: "German" },
        { id: 69, class_id: 6, name: "Regional Language" },

        { id: 70, class_id: 7, name: "Mathematics" },
        { id: 71, class_id: 7, name: "Science" },
        { id: 72, class_id: 7, name: "Social Science" },
        { id: 73, class_id: 7, name: "English" },
        { id: 74, class_id: 7, name: "हिंदी (वसंत और बाल महाभारत कथा)" },
        { id: 75, class_id: 7, name: "Other Subjects" },
        { id: 76, class_id: 7, name: "Sanskrit" },
        { id: 77, class_id: 7, name: "Computer" },
        { id: 78, class_id: 7, name: "French" },
        { id: 79, class_id: 7, name: "German" },
        { id: 80, class_id: 7, name: "Regional Language" },

        { id: 81, class_id: 8, name: "Mathematics" },
        { id: 82, class_id: 8, name: "Science" },
        { id: 83, class_id: 8, name: "Social Science" },
        { id: 84, class_id: 8, name: "Sanskrit" },
        { id: 85, class_id: 8, name: "Computer" },
        { id: 86, class_id: 8, name: "French" },
        { id: 87, class_id: 8, name: "German" },
        { id: 88, class_id: 8, name: "Regional Language" },
        { id: 89, class_id: 8, name: "English" },
        { id: 90, class_id: 8, name: "हिंदी (वसंत और भारत की खोज)" },
        { id: 91, class_id: 8, name: "Other Subjects" },

        { id: 92, class_id: 9, name: "Science" },
        { id: 93, class_id: 9, name: "Mathematics" },
        { id: 94, class_id: 9, name: "Information Technology (402)" },
        { id: 95, class_id: 9, name: "German" },
        { id: 96, class_id: 9, name: "Regional Language" },
        { id: 97, class_id: 9, name: "Social Science" },
        { id: 98, class_id: 9, name: "सामाजिक विज्ञान" },
        { id: 99, class_id: 9, name: "English" },
        { id: 100, class_id: 9, name: "Hindi A" },
        { id: 101, class_id: 9, name: "Hindi B" },
        { id: 102, class_id: 9, name: "Computer Applications" },
        { id: 103, class_id: 9, name: "JSTSE Scholarship" },
        { id: 104, class_id: 9, name: "संस्कृत (शेमुषी)" },
        { id: 105, class_id: 9, name: "French" },
        { id: 106, class_id: 9, name: "Painting" },
        { id: 107, class_id: 9, name: "Home Science" },
        { id: 108, class_id: 9, name: "Music" },
        { id: 109, class_id: 9, name: "Other Subjects" },

        { id: 110, class_id: 10, name: "Mathematics" },
        { id: 111, class_id: 10, name: "Science" },
        { id: 112, class_id: 10, name: "विज्ञान" },
        { id: 113, class_id: 10, name: "Information Technology (402)" },
        { id: 114, class_id: 10, name: "German" },
        { id: 115, class_id: 10, name: "Regional Language" },
        { id: 116, class_id: 10, name: "Social Science" },
        { id: 117, class_id: 10, name: "सामाजिक विज्ञान" },
        { id: 118, class_id: 10, name: "English" },
        { id: 119, class_id: 10, name: "Hindi A" },
        { id: 120, class_id: 10, name: "Hindi B" },
        { id: 121, class_id: 10, name: "Computer Applications" },
        { id: 122, class_id: 10, name: "NTSE Scholarship" },
        { id: 123, class_id: 10, name: "संस्कृत (शेमुषी)" },
        { id: 124, class_id: 10, name: "French" },
        { id: 125, class_id: 10, name: "Painting" },
        { id: 126, class_id: 10, name: "Home Science" },
        { id: 127, class_id: 10, name: "Music" },
        { id: 128, class_id: 10, name: "Other Subjects" },

        { id: 129, class_id: 11, name: "Physics" },
        { id: 130, class_id: 11, name: "Chemistry" },
        { id: 131, class_id: 11, name: "Mathematics" },
        { id: 132, class_id: 11, name: "Biology" },
        { id: 133, class_id: 11, name: "Accountancy" },
        { id: 134, class_id: 11, name: "Economics" },
        { id: 135, class_id: 11, name: "अर्थशास्त्र" },
        { id: 136, class_id: 11, name: "Business Studies" },
        { id: 137, class_id: 11, name: "व्यवसाय अध्ययन" },
        { id: 138, class_id: 11, name: "Applied Mathematics" },
        { id: 139, class_id: 11, name: "Painting" },
        { id: 140, class_id: 11, name: "Computer Science" },
        { id: 141, class_id: 11, name: "Informatics Practices" },
        { id: 142, class_id: 11, name: "English Core" },
        { id: 143, class_id: 11, name: "English Elective NCERT" },
        { id: 144, class_id: 11, name: "Hindi Core" },
        { id: 145, class_id: 11, name: "Hindi Elective" },
        { id: 146, class_id: 11, name: "History" },
        { id: 147, class_id: 11, name: "इतिहास" },
        { id: 148, class_id: 11, name: "Political Science" },
        { id: 149, class_id: 11, name: "राजनीति विज्ञान" },
        { id: 150, class_id: 11, name: "Geography" },
        { id: 151, class_id: 11, name: "भूगोल" },
        { id: 152, class_id: 11, name: "Sociology" },
        { id: 153, class_id: 11, name: "समाजशास्त्र" },
        { id: 154, class_id: 11, name: "Engineering Graphics" },
        { id: 155, class_id: 11, name: "Home Science" },
        { id: 156, class_id: 11, name: "Physical Education" },
        { id: 157, class_id: 11, name: "शारीरिक शिक्षा" },
        { id: 158, class_id: 11, name: "Multimedia and Webtech" },
        { id: 159, class_id: 11, name: "Entrepreneurship" },
        { id: 160, class_id: 11, name: "Sanskrit Core" },
        { id: 161, class_id: 11, name: "Sanskrit Elective" },
        { id: 162, class_id: 11, name: "Psychology" },
        { id: 163, class_id: 11, name: "Biotechnology" },
        { id: 164, class_id: 11, name: "Legal Studies" },
        { id: 165, class_id: 11, name: "Financial Market Management" },
        { id: 166, class_id: 11, name: "Other Subjects" },

        { id: 167, class_id: 12, name: "Physics" },
        { id: 168, class_id: 12, name: "Chemistry" },
        { id: 169, class_id: 12, name: "Mathematics" },
        { id: 170, class_id: 12, name: "Applied Mathematics" },
        { id: 171, class_id: 12, name: "Biology" },
        { id: 172, class_id: 12, name: "Accountancy" },
        { id: 173, class_id: 12, name: "Economics" },
        { id: 174, class_id: 12, name: "अर्थशास्त्र" },
        { id: 175, class_id: 12, name: "Business Studies" },
        { id: 176, class_id: 12, name: "व्यवसाय अध्ययन" },
        { id: 177, class_id: 12, name: "Painting" },
        { id: 178, class_id: 12, name: "Computer Science" },
        { id: 179, class_id: 12, name: "Informatics Practices" },
        { id: 180, class_id: 12, name: "English Core" },
        { id: 181, class_id: 12, name: "English Elective NCERT" },
        { id: 182, class_id: 12, name: "हिंदी कोर" },
        { id: 183, class_id: 12, name: "हिंदी ऐच्छिक" },
        { id: 184, class_id: 12, name: "History" },
        { id: 185, class_id: 12, name: "इतिहास" },
        { id: 186, class_id: 12, name: "Political Science" },
        { id: 187, class_id: 12, name: "राजनीति विज्ञान" },
        { id: 188, class_id: 12, name: "Geography" },
        { id: 189, class_id: 12, name: "भूगोल" },
        { id: 190, class_id: 12, name: "Sociology" },
        { id: 191, class_id: 12, name: "समाजशास्त्र" },
        { id: 192, class_id: 12, name: "Engineering Graphics" },
        { id: 193, class_id: 12, name: "Home Science" },
        { id: 194, class_id: 12, name: "Physical Education" },
        { id: 195, class_id: 12, name: "शारीरिक शिक्षा" },
        { id: 196, class_id: 12, name: "Multimedia and Webtech" },
        { id: 197, class_id: 12, name: "Entrepreneurship" },
        { id: 198, class_id: 12, name: "संस्कृत कोर (भास्वती)" },
        { id: 199, class_id: 12, name: "संस्कृत ऐच्छिक" },
        { id: 200, class_id: 12, name: "Psychology" },
        { id: 201, class_id: 12, name: "Biotechnology" },
        { id: 202, class_id: 12, name: "Legal Studies" },
        { id: 203, class_id: 12, name: "Financial Market Management" },
        { id: 204, class_id: 12, name: "Other Subjects" },

        { id: 205, class_id: 13, name: "Physics" },
        { id: 206, class_id: 13, name: "Chemistry" },
        { id: 207, class_id: 13, name: "Mathematics" },

        { id: 208, class_id: 14, name: "Physics" },
        { id: 209, class_id: 14, name: "Chemistry" },
        { id: 210, class_id: 14, name: "Biology" },

        { id: 211, class_id: 15, name: "Intelligence and Reasoning" },
        { id: 212, class_id: 15, name: "General Awareness" },
        { id: 213, class_id: 15, name: "Quantitative Aptitude" },
        { id: 214, class_id: 15, name: "English Comprehension" },

        { id: 215, class_id: 16, name: "Mathematics" },
        { id: 216, class_id: 16, name: "English" },
        { id: 217, class_id: 16, name: "General Knowledge" },

        { id: 218, class_id: 17, name: "Others" },
        { id: 219, class_id: 18, name: "Others" },
        { id: 220, class_id: 19, name: "Others" },
        { id: 221, class_id: 20, name: "Others" },
        { id: 222, class_id: 21, name: "Others" },

        { id: 223, class_id: 22, name: "English" },
        { id: 224, class_id: 22, name: "Hindi" },
        { id: 225, class_id: 22, name: "Mathematics" },
        { id: 226, class_id: 22, name: "History & Civics" },
        { id: 227, class_id: 22, name: "Geography" },
        { id: 228, class_id: 22, name: "Physics" },
        { id: 229, class_id: 22, name: "Chemistry" },
        { id: 230, class_id: 22, name: "Biology" },
        { id: 231, class_id: 22, name: "Computer Studies" },
        { id: 232, class_id: 22, name: "Others" },

        { id: 233, class_id: 23, name: "English" },
        { id: 234, class_id: 23, name: "Hindi" },
        { id: 235, class_id: 23, name: "Mathematics" },
        { id: 236, class_id: 23, name: "History & Civics" },
        { id: 237, class_id: 23, name: "Geography" },
        { id: 238, class_id: 23, name: "Physics" },
        { id: 239, class_id: 23, name: "Chemistry" },
        { id: 240, class_id: 23, name: "Biology" },
        { id: 241, class_id: 23, name: "Computer Studies" },
        { id: 242, class_id: 23, name: "Others" },

        { id: 243, class_id: 24, name: "English" },
        { id: 244, class_id: 24, name: "Hindi" },
        { id: 245, class_id: 24, name: "Mathematics" },
        { id: 246, class_id: 24, name: "History & Civics" },
        { id: 247, class_id: 24, name: "Geography" },
        { id: 248, class_id: 24, name: "Physics" },
        { id: 249, class_id: 24, name: "Chemistry" },
        { id: 250, class_id: 24, name: "Biology" },
        { id: 251, class_id: 24, name: "Computer Studies" },
        { id: 252, class_id: 24, name: "Others" },

        { id: 253, class_id: 25, name: "English" },
        { id: 254, class_id: 25, name: "Hindi" },
        { id: 255, class_id: 25, name: "Mathematics" },
        { id: 256, class_id: 25, name: "History & Civics" },
        { id: 257, class_id: 25, name: "Geography" },
        { id: 258, class_id: 25, name: "Physics" },
        { id: 259, class_id: 25, name: "Chemistry" },
        { id: 260, class_id: 25, name: "Biology" },
        { id: 261, class_id: 25, name: "Computer Studies" },
        { id: 262, class_id: 25, name: "Others" },

        { id: 263, class_id: 26, name: "Physics" },
        { id: 264, class_id: 26, name: "Chemistry" },
        { id: 265, class_id: 26, name: "Mathematics" },
        { id: 266, class_id: 26, name: "Biology" },
        { id: 267, class_id: 26, name: "Economics" },
        { id: 268, class_id: 26, name: "Literature in English" },
        { id: 269, class_id: 26, name: "English Language" },
        { id: 270, class_id: 26, name: "History and Civics" },
        { id: 271, class_id: 26, name: "Geography" },
        { id: 272, class_id: 26, name: "Hindi" },
        { id: 273, class_id: 26, name: "Other Subjects" },

        { id: 274, class_id: 27, name: "Physics" },
        { id: 275, class_id: 27, name: "Chemistry" },
        { id: 276, class_id: 27, name: "Mathematics" },
        { id: 277, class_id: 27, name: "Biology" },
        { id: 278, class_id: 27, name: "Accountancy" },
        { id: 279, class_id: 27, name: "Economics" },
        { id: 280, class_id: 27, name: "Business Studies" },
        { id: 281, class_id: 27, name: "Literature in English" },
        { id: 282, class_id: 27, name: "English Language" },
        { id: 283, class_id: 27, name: "Hindi" },
        { id: 284, class_id: 27, name: "History" },
        { id: 285, class_id: 27, name: "Political Science" },
        { id: 286, class_id: 27, name: "Geography" },
        { id: 287, class_id: 27, name: "Other Subjects" },

        { id: 288, class_id: 28, name: "Physics" },
        { id: 289, class_id: 28, name: "Chemistry" },
        { id: 290, class_id: 28, name: "Mathematics" },
        { id: 291, class_id: 28, name: "Biology" },
        { id: 292, class_id: 28, name: "Accountancy" },
        { id: 293, class_id: 28, name: "Economics" },
        { id: 294, class_id: 28, name: "Business Studies" },
        { id: 295, class_id: 28, name: "Literature in English" },
        { id: 296, class_id: 28, name: "English Language" },
        { id: 297, class_id: 28, name: "Hindi" },
        { id: 298, class_id: 28, name: "History" },
        { id: 299, class_id: 28, name: "Political Science" },
        { id: 300, class_id: 28, name: "Geography" },
        { id: 301, class_id: 28, name: "Other Subjects" },
        
        { id: 302, class_id: 29, name: "Others" },
      ]);
    });
};
